"""execution du reste des tables

Revision ID: 875a648387b4
Revises: 3af9b11952b3
Create Date: 2026-09-07 15:04:35.917267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875a648387b4'
down_revision: Union[str, None] = '3af9b11952b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poultry_lots',
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_purchase_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_dues',
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'overdue', name='insuranceduestatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['insurance_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_dues_contract_id'), 'insurance_dues', ['contract_id'], unique=False)
    op.create_table('poultry_purchases',
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['poultry_lots.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_poultry_purchases_lot_id'), 'poultry_purchases', ['lot_id'], unique=True)
    op.create_table('poultry_sales',
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('poultry_sale_lots',
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_taken', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['poultry_lots.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['poultry_sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poultry_sale_lots_lot_id'), 'poultry_sale_lots', ['lot_id'], unique=False)
    op.create_index(op.f('ix_poultry_sale_lots_sale_id'), 'poultry_sale_lots', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poultry_sale_lots_sale_id'), table_name='poultry_sale_lots')
    op.drop_index(op.f('ix_poultry_sale_lots_lot_id'), table_name='poultry_sale_lots')
    op.drop_table('poultry_sale_lots')
    op.drop_table('poultry_sales')
    op.drop_index(op.f('ix_poultry_purchases_lot_id'), table_name='poultry_purchases')
    op.drop_table('poultry_purchases')
    op.drop_index(op.f('ix_insurance_dues_contract_id'), table_name='insurance_dues')
    op.drop_table('insurance_dues')
    op.drop_table('poultry_lots')
    # ### end Alembic commands ###
