"""ajout des tables VTC

Revision ID: dedcb6543ab6
Revises: 875a648387b4
Create Date: 2026-09-11 15:57:17.368475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dedcb6543ab6'
down_revision: Union[str, None] = '875a648387b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='chauffeurstatut', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_person_id'), 'drivers', ['person_id'], unique=True)
    op.create_table('vehicles',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('registration', sa.String(length=50), nullable=False),
    sa.Column('acquisition_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('acquisition_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'out_of_service', 'sold', name='vehiculestatut', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_business_id'), 'vehicles', ['business_id'], unique=False)
    op.create_index(op.f('ix_vehicles_registration'), 'vehicles', ['registration'], unique=True)
    op.create_table('vehicle_assignments',
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('terms', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('active', 'ended', name='affectationstatut', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_assignments_driver_id'), 'vehicle_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_vehicle_id'), 'vehicle_assignments', ['vehicle_id'], unique=False)
    op.create_table('vehicle_downtimes',
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_downtimes_vehicle_id'), 'vehicle_downtimes', ['vehicle_id'], unique=False)
    op.create_table('vehicle_expenses',
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('expense_type', sa.Enum('fuel', 'maintenance', 'repair', 'tires', 'insurance', 'registration', 'misc', name='typedepensevehicule', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_vehicle_expenses_vehicle_id'), 'vehicle_expenses', ['vehicle_id'], unique=False)
    op.create_table('driver_remittances',
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['vehicle_assignments.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_driver_remittances_assignment_id'), 'driver_remittances', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_driver_remittances_driver_id'), 'driver_remittances', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_remittances_vehicle_id'), 'driver_remittances', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_remittances_vehicle_id'), table_name='driver_remittances')
    op.drop_index(op.f('ix_driver_remittances_driver_id'), table_name='driver_remittances')
    op.drop_index(op.f('ix_driver_remittances_assignment_id'), table_name='driver_remittances')
    op.drop_table('driver_remittances')
    op.drop_index(op.f('ix_vehicle_expenses_vehicle_id'), table_name='vehicle_expenses')
    op.drop_table('vehicle_expenses')
    op.drop_index(op.f('ix_vehicle_downtimes_vehicle_id'), table_name='vehicle_downtimes')
    op.drop_table('vehicle_downtimes')
    op.drop_index(op.f('ix_vehicle_assignments_vehicle_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_driver_id'), table_name='vehicle_assignments')
    op.drop_table('vehicle_assignments')
    op.drop_index(op.f('ix_vehicles_registration'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_business_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_drivers_person_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
